name: CI/CD for WTA

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Project
        run: npm run build
      - name: Check Linting
        run: npm run lint
      - name: Check Linting Coverage
        run: npm run lint --coverage
